---
-- Created by IntelliJ IDEA.
-- User: ZenX2
-- Date: 11/21/11
-- Time: 6:14 PM
--
--CLIENT

--TODO: Client object for server
--TODO: Input struct for CLIENT -> SERVER
--TODO: MOVEY THINGYS SERVER -> CLIENT; draw stuff
--TODO: CLIENT DRAWY STUFF AND ALL THAT